### ISSUE TITLE
Je bent nog niet ver genoeg. kan je nog ff tot blz 300 werken plz

### ISSUE THREAD

**Issue by AlexSpelt** [brian8544/Frontend-Programmeren#1]

**Comment by AlexSpelt** [comment]
Als je toch al bezig ben werk dan ook ff tot 360 dat is voor de volgende 4 weken zegmaar.

**Comment by brian8544** [comment]
Als je 't zelf nou maakt, stuur je 'n pull naar mij toe ;)
